# Generated by Django 3.1.1 on 2020-09-30 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200930_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='comments',
        ),
        migrations.AddField(
            model_name='comments',
            name='comment_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_item', to='auctions.listings'),
        ),
    ]
