# Generated by Django 3.1.1 on 2020-10-01 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_listings_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bids',
            new_name='Bid',
        ),
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='Listings',
            new_name='Listing',
        ),
    ]
