# Generated by Django 3.1.1 on 2020-10-02 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20201002_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(upload_to='auctions/static/images'),
        ),
    ]
